// @generated by protoc-gen-es v1.4.2 with parameter "target=ts"
// @generated from file neutron/cron/schedule.proto (package neutron.cron, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64 } from "@bufbuild/protobuf";

/**
 * @generated from message neutron.cron.Schedule
 */
export class Schedule extends Message<Schedule> {
  /**
   * Name of schedule
   *
   * @generated from field: string name = 1;
   */
  name = "";

  /**
   * Period in blocks
   *
   * @generated from field: uint64 period = 2;
   */
  period = protoInt64.zero;

  /**
   * Msgs that will be executed every period amount of time
   *
   * @generated from field: repeated neutron.cron.MsgExecuteContract msgs = 3;
   */
  msgs: MsgExecuteContract[] = [];

  /**
   * Last execution's block height
   *
   * @generated from field: uint64 last_execute_height = 4;
   */
  lastExecuteHeight = protoInt64.zero;

  constructor(data?: PartialMessage<Schedule>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "neutron.cron.Schedule";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "period", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 3, name: "msgs", kind: "message", T: MsgExecuteContract, repeated: true },
    { no: 4, name: "last_execute_height", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Schedule {
    return new Schedule().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Schedule {
    return new Schedule().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Schedule {
    return new Schedule().fromJsonString(jsonString, options);
  }

  static equals(a: Schedule | PlainMessage<Schedule> | undefined, b: Schedule | PlainMessage<Schedule> | undefined): boolean {
    return proto3.util.equals(Schedule, a, b);
  }
}

/**
 * @generated from message neutron.cron.MsgExecuteContract
 */
export class MsgExecuteContract extends Message<MsgExecuteContract> {
  /**
   * Contract is the address of the smart contract
   *
   * @generated from field: string contract = 1;
   */
  contract = "";

  /**
   * Msg is json encoded message to be passed to the contract
   *
   * @generated from field: string msg = 2;
   */
  msg = "";

  constructor(data?: PartialMessage<MsgExecuteContract>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "neutron.cron.MsgExecuteContract";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "contract", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "msg", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MsgExecuteContract {
    return new MsgExecuteContract().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MsgExecuteContract {
    return new MsgExecuteContract().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MsgExecuteContract {
    return new MsgExecuteContract().fromJsonString(jsonString, options);
  }

  static equals(a: MsgExecuteContract | PlainMessage<MsgExecuteContract> | undefined, b: MsgExecuteContract | PlainMessage<MsgExecuteContract> | undefined): boolean {
    return proto3.util.equals(MsgExecuteContract, a, b);
  }
}

/**
 * @generated from message neutron.cron.ScheduleCount
 */
export class ScheduleCount extends Message<ScheduleCount> {
  /**
   * Count is the number of current schedules
   *
   * @generated from field: int32 count = 1;
   */
  count = 0;

  constructor(data?: PartialMessage<ScheduleCount>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "neutron.cron.ScheduleCount";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "count", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ScheduleCount {
    return new ScheduleCount().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ScheduleCount {
    return new ScheduleCount().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ScheduleCount {
    return new ScheduleCount().fromJsonString(jsonString, options);
  }

  static equals(a: ScheduleCount | PlainMessage<ScheduleCount> | undefined, b: ScheduleCount | PlainMessage<ScheduleCount> | undefined): boolean {
    return proto3.util.equals(ScheduleCount, a, b);
  }
}

