// @generated by protoc-gen-es v1.4.2 with parameter "target=ts"
// @generated from file neutron/interchainqueries/tx.proto (package neutron.interchainqueries, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Any, Message, proto3, protoInt64 } from "@bufbuild/protobuf";
import { KVKey } from "./genesis_pb.js";
import { Proof, ProofOps } from "../../tendermint/crypto/proof_pb.js";
import { ExecTxResult } from "../../tendermint/abci/types_pb.js";
import { Params } from "./params_pb.js";

/**
 * @generated from message neutron.interchainqueries.MsgRegisterInterchainQuery
 */
export class MsgRegisterInterchainQuery extends Message<MsgRegisterInterchainQuery> {
  /**
   * defines a query type: `kv` or `tx` now
   *
   * @generated from field: string query_type = 1;
   */
  queryType = "";

  /**
   * is used to define KV-storage keys for which we want to get values from
   * remote chain
   *
   * @generated from field: repeated neutron.interchainqueries.KVKey keys = 2;
   */
  keys: KVKey[] = [];

  /**
   * is used to define a filter for transaction search ICQ
   *
   * @generated from field: string transactions_filter = 3;
   */
  transactionsFilter = "";

  /**
   * is IBC connection ID for getting ConsensusState to verify proofs
   *
   * @generated from field: string connection_id = 4;
   */
  connectionId = "";

  /**
   * is used to specify how often (in neutron blocks) the query must be updated
   *
   * @generated from field: uint64 update_period = 5;
   */
  updatePeriod = protoInt64.zero;

  /**
   * is the signer of the message
   *
   * @generated from field: string sender = 6;
   */
  sender = "";

  constructor(data?: PartialMessage<MsgRegisterInterchainQuery>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "neutron.interchainqueries.MsgRegisterInterchainQuery";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "query_type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "keys", kind: "message", T: KVKey, repeated: true },
    { no: 3, name: "transactions_filter", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "connection_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "update_period", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 6, name: "sender", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MsgRegisterInterchainQuery {
    return new MsgRegisterInterchainQuery().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MsgRegisterInterchainQuery {
    return new MsgRegisterInterchainQuery().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MsgRegisterInterchainQuery {
    return new MsgRegisterInterchainQuery().fromJsonString(jsonString, options);
  }

  static equals(a: MsgRegisterInterchainQuery | PlainMessage<MsgRegisterInterchainQuery> | undefined, b: MsgRegisterInterchainQuery | PlainMessage<MsgRegisterInterchainQuery> | undefined): boolean {
    return proto3.util.equals(MsgRegisterInterchainQuery, a, b);
  }
}

/**
 * @generated from message neutron.interchainqueries.MsgRegisterInterchainQueryResponse
 */
export class MsgRegisterInterchainQueryResponse extends Message<MsgRegisterInterchainQueryResponse> {
  /**
   * @generated from field: uint64 id = 1;
   */
  id = protoInt64.zero;

  constructor(data?: PartialMessage<MsgRegisterInterchainQueryResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "neutron.interchainqueries.MsgRegisterInterchainQueryResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MsgRegisterInterchainQueryResponse {
    return new MsgRegisterInterchainQueryResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MsgRegisterInterchainQueryResponse {
    return new MsgRegisterInterchainQueryResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MsgRegisterInterchainQueryResponse {
    return new MsgRegisterInterchainQueryResponse().fromJsonString(jsonString, options);
  }

  static equals(a: MsgRegisterInterchainQueryResponse | PlainMessage<MsgRegisterInterchainQueryResponse> | undefined, b: MsgRegisterInterchainQueryResponse | PlainMessage<MsgRegisterInterchainQueryResponse> | undefined): boolean {
    return proto3.util.equals(MsgRegisterInterchainQueryResponse, a, b);
  }
}

/**
 * @generated from message neutron.interchainqueries.MsgSubmitQueryResult
 */
export class MsgSubmitQueryResult extends Message<MsgSubmitQueryResult> {
  /**
   * @generated from field: uint64 query_id = 1;
   */
  queryId = protoInt64.zero;

  /**
   * @generated from field: string sender = 2;
   */
  sender = "";

  /**
   * is the IBC client ID for an IBC connection between Neutron chain and target
   * chain (where the result was obtained from)
   *
   * @generated from field: string client_id = 3;
   */
  clientId = "";

  /**
   * @generated from field: neutron.interchainqueries.QueryResult result = 4;
   */
  result?: QueryResult;

  constructor(data?: PartialMessage<MsgSubmitQueryResult>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "neutron.interchainqueries.MsgSubmitQueryResult";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "query_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 2, name: "sender", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "client_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "result", kind: "message", T: QueryResult },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MsgSubmitQueryResult {
    return new MsgSubmitQueryResult().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MsgSubmitQueryResult {
    return new MsgSubmitQueryResult().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MsgSubmitQueryResult {
    return new MsgSubmitQueryResult().fromJsonString(jsonString, options);
  }

  static equals(a: MsgSubmitQueryResult | PlainMessage<MsgSubmitQueryResult> | undefined, b: MsgSubmitQueryResult | PlainMessage<MsgSubmitQueryResult> | undefined): boolean {
    return proto3.util.equals(MsgSubmitQueryResult, a, b);
  }
}

/**
 * @generated from message neutron.interchainqueries.QueryResult
 */
export class QueryResult extends Message<QueryResult> {
  /**
   * @generated from field: repeated neutron.interchainqueries.StorageValue kv_results = 1;
   */
  kvResults: StorageValue[] = [];

  /**
   * @generated from field: neutron.interchainqueries.Block block = 2;
   */
  block?: Block;

  /**
   * @generated from field: uint64 height = 3;
   */
  height = protoInt64.zero;

  /**
   * @generated from field: uint64 revision = 4;
   */
  revision = protoInt64.zero;

  /**
   * @generated from field: bool allow_kv_callbacks = 5;
   */
  allowKvCallbacks = false;

  constructor(data?: PartialMessage<QueryResult>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "neutron.interchainqueries.QueryResult";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "kv_results", kind: "message", T: StorageValue, repeated: true },
    { no: 2, name: "block", kind: "message", T: Block },
    { no: 3, name: "height", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 4, name: "revision", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 5, name: "allow_kv_callbacks", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryResult {
    return new QueryResult().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryResult {
    return new QueryResult().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryResult {
    return new QueryResult().fromJsonString(jsonString, options);
  }

  static equals(a: QueryResult | PlainMessage<QueryResult> | undefined, b: QueryResult | PlainMessage<QueryResult> | undefined): boolean {
    return proto3.util.equals(QueryResult, a, b);
  }
}

/**
 * @generated from message neutron.interchainqueries.StorageValue
 */
export class StorageValue extends Message<StorageValue> {
  /**
   * is the substore name (acc, staking, etc.)
   *
   * @generated from field: string storage_prefix = 1;
   */
  storagePrefix = "";

  /**
   * is the key in IAVL store
   *
   * @generated from field: bytes key = 2;
   */
  key = new Uint8Array(0);

  /**
   * is the value in IAVL store
   *
   * @generated from field: bytes value = 3;
   */
  value = new Uint8Array(0);

  /**
   * is the Merkle Proof which proves existence of key-value pair in IAVL
   * storage
   *
   * @generated from field: tendermint.crypto.ProofOps Proof = 4;
   */
  Proof?: ProofOps;

  constructor(data?: PartialMessage<StorageValue>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "neutron.interchainqueries.StorageValue";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "storage_prefix", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "key", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
    { no: 3, name: "value", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
    { no: 4, name: "Proof", kind: "message", T: ProofOps },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): StorageValue {
    return new StorageValue().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): StorageValue {
    return new StorageValue().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): StorageValue {
    return new StorageValue().fromJsonString(jsonString, options);
  }

  static equals(a: StorageValue | PlainMessage<StorageValue> | undefined, b: StorageValue | PlainMessage<StorageValue> | undefined): boolean {
    return proto3.util.equals(StorageValue, a, b);
  }
}

/**
 * @generated from message neutron.interchainqueries.Block
 */
export class Block extends Message<Block> {
  /**
   * We need to know block X+1 to verify response of transaction for block X
   * since LastResultsHash is root hash of all results from the txs from the
   * previous block
   *
   * @generated from field: google.protobuf.Any next_block_header = 1;
   */
  nextBlockHeader?: Any;

  /**
   * We need to know block X to verify inclusion of transaction for block X
   *
   * @generated from field: google.protobuf.Any header = 2;
   */
  header?: Any;

  /**
   * @generated from field: neutron.interchainqueries.TxValue tx = 3;
   */
  tx?: TxValue;

  constructor(data?: PartialMessage<Block>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "neutron.interchainqueries.Block";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "next_block_header", kind: "message", T: Any },
    { no: 2, name: "header", kind: "message", T: Any },
    { no: 3, name: "tx", kind: "message", T: TxValue },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Block {
    return new Block().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Block {
    return new Block().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Block {
    return new Block().fromJsonString(jsonString, options);
  }

  static equals(a: Block | PlainMessage<Block> | undefined, b: Block | PlainMessage<Block> | undefined): boolean {
    return proto3.util.equals(Block, a, b);
  }
}

/**
 * @generated from message neutron.interchainqueries.TxValue
 */
export class TxValue extends Message<TxValue> {
  /**
   * @generated from field: tendermint.abci.ExecTxResult response = 1;
   */
  response?: ExecTxResult;

  /**
   * is the Merkle Proof which proves existence of response in block with height
   * next_block_header.Height
   *
   * @generated from field: tendermint.crypto.Proof delivery_proof = 2;
   */
  deliveryProof?: Proof;

  /**
   * is the Merkle Proof which proves existence of data in block with height
   * header.Height
   *
   * @generated from field: tendermint.crypto.Proof inclusion_proof = 3;
   */
  inclusionProof?: Proof;

  /**
   * is body of the transaction
   *
   * @generated from field: bytes data = 4;
   */
  data = new Uint8Array(0);

  constructor(data?: PartialMessage<TxValue>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "neutron.interchainqueries.TxValue";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "response", kind: "message", T: ExecTxResult },
    { no: 2, name: "delivery_proof", kind: "message", T: Proof },
    { no: 3, name: "inclusion_proof", kind: "message", T: Proof },
    { no: 4, name: "data", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): TxValue {
    return new TxValue().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): TxValue {
    return new TxValue().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): TxValue {
    return new TxValue().fromJsonString(jsonString, options);
  }

  static equals(a: TxValue | PlainMessage<TxValue> | undefined, b: TxValue | PlainMessage<TxValue> | undefined): boolean {
    return proto3.util.equals(TxValue, a, b);
  }
}

/**
 * @generated from message neutron.interchainqueries.MsgSubmitQueryResultResponse
 */
export class MsgSubmitQueryResultResponse extends Message<MsgSubmitQueryResultResponse> {
  constructor(data?: PartialMessage<MsgSubmitQueryResultResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "neutron.interchainqueries.MsgSubmitQueryResultResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MsgSubmitQueryResultResponse {
    return new MsgSubmitQueryResultResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MsgSubmitQueryResultResponse {
    return new MsgSubmitQueryResultResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MsgSubmitQueryResultResponse {
    return new MsgSubmitQueryResultResponse().fromJsonString(jsonString, options);
  }

  static equals(a: MsgSubmitQueryResultResponse | PlainMessage<MsgSubmitQueryResultResponse> | undefined, b: MsgSubmitQueryResultResponse | PlainMessage<MsgSubmitQueryResultResponse> | undefined): boolean {
    return proto3.util.equals(MsgSubmitQueryResultResponse, a, b);
  }
}

/**
 * @generated from message neutron.interchainqueries.MsgRemoveInterchainQueryRequest
 */
export class MsgRemoveInterchainQueryRequest extends Message<MsgRemoveInterchainQueryRequest> {
  /**
   * @generated from field: uint64 query_id = 1;
   */
  queryId = protoInt64.zero;

  /**
   * is the signer of the message
   *
   * @generated from field: string sender = 2;
   */
  sender = "";

  constructor(data?: PartialMessage<MsgRemoveInterchainQueryRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "neutron.interchainqueries.MsgRemoveInterchainQueryRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "query_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 2, name: "sender", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MsgRemoveInterchainQueryRequest {
    return new MsgRemoveInterchainQueryRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MsgRemoveInterchainQueryRequest {
    return new MsgRemoveInterchainQueryRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MsgRemoveInterchainQueryRequest {
    return new MsgRemoveInterchainQueryRequest().fromJsonString(jsonString, options);
  }

  static equals(a: MsgRemoveInterchainQueryRequest | PlainMessage<MsgRemoveInterchainQueryRequest> | undefined, b: MsgRemoveInterchainQueryRequest | PlainMessage<MsgRemoveInterchainQueryRequest> | undefined): boolean {
    return proto3.util.equals(MsgRemoveInterchainQueryRequest, a, b);
  }
}

/**
 * @generated from message neutron.interchainqueries.MsgRemoveInterchainQueryResponse
 */
export class MsgRemoveInterchainQueryResponse extends Message<MsgRemoveInterchainQueryResponse> {
  constructor(data?: PartialMessage<MsgRemoveInterchainQueryResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "neutron.interchainqueries.MsgRemoveInterchainQueryResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MsgRemoveInterchainQueryResponse {
    return new MsgRemoveInterchainQueryResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MsgRemoveInterchainQueryResponse {
    return new MsgRemoveInterchainQueryResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MsgRemoveInterchainQueryResponse {
    return new MsgRemoveInterchainQueryResponse().fromJsonString(jsonString, options);
  }

  static equals(a: MsgRemoveInterchainQueryResponse | PlainMessage<MsgRemoveInterchainQueryResponse> | undefined, b: MsgRemoveInterchainQueryResponse | PlainMessage<MsgRemoveInterchainQueryResponse> | undefined): boolean {
    return proto3.util.equals(MsgRemoveInterchainQueryResponse, a, b);
  }
}

/**
 * @generated from message neutron.interchainqueries.MsgUpdateInterchainQueryRequest
 */
export class MsgUpdateInterchainQueryRequest extends Message<MsgUpdateInterchainQueryRequest> {
  /**
   * @generated from field: uint64 query_id = 1;
   */
  queryId = protoInt64.zero;

  /**
   * @generated from field: repeated neutron.interchainqueries.KVKey new_keys = 2;
   */
  newKeys: KVKey[] = [];

  /**
   * @generated from field: uint64 new_update_period = 3;
   */
  newUpdatePeriod = protoInt64.zero;

  /**
   * @generated from field: string new_transactions_filter = 4;
   */
  newTransactionsFilter = "";

  /**
   * is the signer of the message
   *
   * @generated from field: string sender = 5;
   */
  sender = "";

  constructor(data?: PartialMessage<MsgUpdateInterchainQueryRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "neutron.interchainqueries.MsgUpdateInterchainQueryRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "query_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 2, name: "new_keys", kind: "message", T: KVKey, repeated: true },
    { no: 3, name: "new_update_period", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 4, name: "new_transactions_filter", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "sender", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MsgUpdateInterchainQueryRequest {
    return new MsgUpdateInterchainQueryRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MsgUpdateInterchainQueryRequest {
    return new MsgUpdateInterchainQueryRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MsgUpdateInterchainQueryRequest {
    return new MsgUpdateInterchainQueryRequest().fromJsonString(jsonString, options);
  }

  static equals(a: MsgUpdateInterchainQueryRequest | PlainMessage<MsgUpdateInterchainQueryRequest> | undefined, b: MsgUpdateInterchainQueryRequest | PlainMessage<MsgUpdateInterchainQueryRequest> | undefined): boolean {
    return proto3.util.equals(MsgUpdateInterchainQueryRequest, a, b);
  }
}

/**
 * @generated from message neutron.interchainqueries.MsgUpdateInterchainQueryResponse
 */
export class MsgUpdateInterchainQueryResponse extends Message<MsgUpdateInterchainQueryResponse> {
  constructor(data?: PartialMessage<MsgUpdateInterchainQueryResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "neutron.interchainqueries.MsgUpdateInterchainQueryResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MsgUpdateInterchainQueryResponse {
    return new MsgUpdateInterchainQueryResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MsgUpdateInterchainQueryResponse {
    return new MsgUpdateInterchainQueryResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MsgUpdateInterchainQueryResponse {
    return new MsgUpdateInterchainQueryResponse().fromJsonString(jsonString, options);
  }

  static equals(a: MsgUpdateInterchainQueryResponse | PlainMessage<MsgUpdateInterchainQueryResponse> | undefined, b: MsgUpdateInterchainQueryResponse | PlainMessage<MsgUpdateInterchainQueryResponse> | undefined): boolean {
    return proto3.util.equals(MsgUpdateInterchainQueryResponse, a, b);
  }
}

/**
 * MsgUpdateParams is the MsgUpdateParams request type.
 *
 * Since: 0.47
 *
 * @generated from message neutron.interchainqueries.MsgUpdateParams
 */
export class MsgUpdateParams extends Message<MsgUpdateParams> {
  /**
   * Authority is the address of the governance account.
   *
   * @generated from field: string authority = 1;
   */
  authority = "";

  /**
   * params defines the x/interchainqueries parameters to update.
   *
   * NOTE: All parameters must be supplied.
   *
   * @generated from field: neutron.interchainqueries.Params params = 2;
   */
  params?: Params;

  constructor(data?: PartialMessage<MsgUpdateParams>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "neutron.interchainqueries.MsgUpdateParams";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "authority", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "params", kind: "message", T: Params },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MsgUpdateParams {
    return new MsgUpdateParams().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MsgUpdateParams {
    return new MsgUpdateParams().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MsgUpdateParams {
    return new MsgUpdateParams().fromJsonString(jsonString, options);
  }

  static equals(a: MsgUpdateParams | PlainMessage<MsgUpdateParams> | undefined, b: MsgUpdateParams | PlainMessage<MsgUpdateParams> | undefined): boolean {
    return proto3.util.equals(MsgUpdateParams, a, b);
  }
}

/**
 * MsgUpdateParamsResponse defines the response structure for executing a
 * MsgUpdateParams message.
 *
 * Since: 0.47
 *
 * @generated from message neutron.interchainqueries.MsgUpdateParamsResponse
 */
export class MsgUpdateParamsResponse extends Message<MsgUpdateParamsResponse> {
  constructor(data?: PartialMessage<MsgUpdateParamsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "neutron.interchainqueries.MsgUpdateParamsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MsgUpdateParamsResponse {
    return new MsgUpdateParamsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MsgUpdateParamsResponse {
    return new MsgUpdateParamsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MsgUpdateParamsResponse {
    return new MsgUpdateParamsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: MsgUpdateParamsResponse | PlainMessage<MsgUpdateParamsResponse> | undefined, b: MsgUpdateParamsResponse | PlainMessage<MsgUpdateParamsResponse> | undefined): boolean {
    return proto3.util.equals(MsgUpdateParamsResponse, a, b);
  }
}

