// @generated by protoc-gen-es v1.4.2 with parameter "target=ts"
// @generated from file slinky/incentives/v1/examples/badprice.proto (package slinky.incentives.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * BadPriceIncentive is a message that contains the information about a bad
 * price that was submitted by a validator.
 *
 * NOTE: This is an example of a bad price incentive. It is not used in
 * production.
 *
 * @generated from message slinky.incentives.v1.BadPriceIncentive
 */
export class BadPriceIncentive extends Message<BadPriceIncentive> {
  /**
   * Validator is the address of the validator that submitted the bad price.
   *
   * @generated from field: string validator = 1;
   */
  validator = "";

  /**
   * Amount is the amount to slash.
   *
   * @generated from field: string amount = 2;
   */
  amount = "";

  constructor(data?: PartialMessage<BadPriceIncentive>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "slinky.incentives.v1.BadPriceIncentive";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "validator", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "amount", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): BadPriceIncentive {
    return new BadPriceIncentive().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): BadPriceIncentive {
    return new BadPriceIncentive().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): BadPriceIncentive {
    return new BadPriceIncentive().fromJsonString(jsonString, options);
  }

  static equals(a: BadPriceIncentive | PlainMessage<BadPriceIncentive> | undefined, b: BadPriceIncentive | PlainMessage<BadPriceIncentive> | undefined): boolean {
    return proto3.util.equals(BadPriceIncentive, a, b);
  }
}

