// @generated by protoc-gen-es v1.4.2 with parameter "target=ts"
// @generated from file neutron/contractmanager/v1/failure.proto (package neutron.contractmanager.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64 } from "@bufbuild/protobuf";

/**
 * Deprecated. Used only for migration purposes.
 *
 * @generated from message neutron.contractmanager.v1.Failure
 */
export class Failure extends Message<Failure> {
  /**
   * ChannelId
   *
   * @generated from field: string channel_id = 1;
   */
  channelId = "";

  /**
   * Address of the failed contract
   *
   * @generated from field: string address = 2;
   */
  address = "";

  /**
   * id of the failure under specific address
   *
   * @generated from field: uint64 id = 3;
   */
  id = protoInt64.zero;

  /**
   * ACK id to restore
   *
   * @generated from field: uint64 ack_id = 4;
   */
  ackId = protoInt64.zero;

  /**
   * Acknowledgement type
   *
   * @generated from field: string ack_type = 5;
   */
  ackType = "";

  constructor(data?: PartialMessage<Failure>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "neutron.contractmanager.v1.Failure";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "channel_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "id", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 4, name: "ack_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 5, name: "ack_type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Failure {
    return new Failure().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Failure {
    return new Failure().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Failure {
    return new Failure().fromJsonString(jsonString, options);
  }

  static equals(a: Failure | PlainMessage<Failure> | undefined, b: Failure | PlainMessage<Failure> | undefined): boolean {
    return proto3.util.equals(Failure, a, b);
  }
}

