// @generated by protoc-gen-es v1.4.2 with parameter "target=ts"
// @generated from file slinky/service/v1/oracle.proto (package slinky.service.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, Timestamp } from "@bufbuild/protobuf";

/**
 * QueryPricesRequest defines the request type for the the Prices method.
 *
 * @generated from message slinky.service.v1.QueryPricesRequest
 */
export class QueryPricesRequest extends Message<QueryPricesRequest> {
  constructor(data?: PartialMessage<QueryPricesRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "slinky.service.v1.QueryPricesRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryPricesRequest {
    return new QueryPricesRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryPricesRequest {
    return new QueryPricesRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryPricesRequest {
    return new QueryPricesRequest().fromJsonString(jsonString, options);
  }

  static equals(a: QueryPricesRequest | PlainMessage<QueryPricesRequest> | undefined, b: QueryPricesRequest | PlainMessage<QueryPricesRequest> | undefined): boolean {
    return proto3.util.equals(QueryPricesRequest, a, b);
  }
}

/**
 * QueryPricesResponse defines the response type for the Prices method.
 *
 * @generated from message slinky.service.v1.QueryPricesResponse
 */
export class QueryPricesResponse extends Message<QueryPricesResponse> {
  /**
   * prices defines the list of prices.
   *
   * @generated from field: map<string, string> prices = 1;
   */
  prices: { [key: string]: string } = {};

  /**
   * @generated from field: google.protobuf.Timestamp timestamp = 2;
   */
  timestamp?: Timestamp;

  constructor(data?: PartialMessage<QueryPricesResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "slinky.service.v1.QueryPricesResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "prices", kind: "map", K: 9 /* ScalarType.STRING */, V: {kind: "scalar", T: 9 /* ScalarType.STRING */} },
    { no: 2, name: "timestamp", kind: "message", T: Timestamp },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryPricesResponse {
    return new QueryPricesResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryPricesResponse {
    return new QueryPricesResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryPricesResponse {
    return new QueryPricesResponse().fromJsonString(jsonString, options);
  }

  static equals(a: QueryPricesResponse | PlainMessage<QueryPricesResponse> | undefined, b: QueryPricesResponse | PlainMessage<QueryPricesResponse> | undefined): boolean {
    return proto3.util.equals(QueryPricesResponse, a, b);
  }
}

