// @generated by protoc-gen-es v1.4.2 with parameter "target=ts"
// @generated from file neutron/interchaintxs/v1/tx.proto (package neutron.interchaintxs.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Any, Message, proto3, protoInt64 } from "@bufbuild/protobuf";
import { Coin } from "../../../cosmos/base/v1beta1/coin_pb.js";
import { Fee } from "../../feerefunder/fee_pb.js";
import { Params } from "./params_pb.js";

/**
 * MsgRegisterInterchainAccount is used to register an account on a remote zone.
 *
 * @generated from message neutron.interchaintxs.v1.MsgRegisterInterchainAccount
 */
export class MsgRegisterInterchainAccount extends Message<MsgRegisterInterchainAccount> {
  /**
   * @generated from field: string from_address = 1;
   */
  fromAddress = "";

  /**
   * @generated from field: string connection_id = 2;
   */
  connectionId = "";

  /**
   * @generated from field: string interchain_account_id = 3;
   */
  interchainAccountId = "";

  /**
   * @generated from field: repeated cosmos.base.v1beta1.Coin register_fee = 4;
   */
  registerFee: Coin[] = [];

  constructor(data?: PartialMessage<MsgRegisterInterchainAccount>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "neutron.interchaintxs.v1.MsgRegisterInterchainAccount";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "from_address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "connection_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "interchain_account_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "register_fee", kind: "message", T: Coin, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MsgRegisterInterchainAccount {
    return new MsgRegisterInterchainAccount().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MsgRegisterInterchainAccount {
    return new MsgRegisterInterchainAccount().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MsgRegisterInterchainAccount {
    return new MsgRegisterInterchainAccount().fromJsonString(jsonString, options);
  }

  static equals(a: MsgRegisterInterchainAccount | PlainMessage<MsgRegisterInterchainAccount> | undefined, b: MsgRegisterInterchainAccount | PlainMessage<MsgRegisterInterchainAccount> | undefined): boolean {
    return proto3.util.equals(MsgRegisterInterchainAccount, a, b);
  }
}

/**
 * MsgRegisterInterchainAccountResponse is the response type for
 * MsgRegisterInterchainAccount.
 *
 * @generated from message neutron.interchaintxs.v1.MsgRegisterInterchainAccountResponse
 */
export class MsgRegisterInterchainAccountResponse extends Message<MsgRegisterInterchainAccountResponse> {
  constructor(data?: PartialMessage<MsgRegisterInterchainAccountResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "neutron.interchaintxs.v1.MsgRegisterInterchainAccountResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MsgRegisterInterchainAccountResponse {
    return new MsgRegisterInterchainAccountResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MsgRegisterInterchainAccountResponse {
    return new MsgRegisterInterchainAccountResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MsgRegisterInterchainAccountResponse {
    return new MsgRegisterInterchainAccountResponse().fromJsonString(jsonString, options);
  }

  static equals(a: MsgRegisterInterchainAccountResponse | PlainMessage<MsgRegisterInterchainAccountResponse> | undefined, b: MsgRegisterInterchainAccountResponse | PlainMessage<MsgRegisterInterchainAccountResponse> | undefined): boolean {
    return proto3.util.equals(MsgRegisterInterchainAccountResponse, a, b);
  }
}

/**
 * MsgSubmitTx defines the payload for Msg/SubmitTx
 *
 * @generated from message neutron.interchaintxs.v1.MsgSubmitTx
 */
export class MsgSubmitTx extends Message<MsgSubmitTx> {
  /**
   * @generated from field: string from_address = 1;
   */
  fromAddress = "";

  /**
   * interchain_account_id is supposed to be the unique identifier, e.g.,
   * lido/kava. This allows contracts to have more than one interchain accounts
   * on remote zone This identifier will be a part of the portID that we'll
   * claim our capability for.
   *
   * @generated from field: string interchain_account_id = 2;
   */
  interchainAccountId = "";

  /**
   * @generated from field: string connection_id = 3;
   */
  connectionId = "";

  /**
   * @generated from field: repeated google.protobuf.Any msgs = 4;
   */
  msgs: Any[] = [];

  /**
   * @generated from field: string memo = 5;
   */
  memo = "";

  /**
   * timeout in seconds after which the packet times out
   *
   * @generated from field: uint64 timeout = 6;
   */
  timeout = protoInt64.zero;

  /**
   * @generated from field: neutron.feerefunder.Fee fee = 7;
   */
  fee?: Fee;

  constructor(data?: PartialMessage<MsgSubmitTx>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "neutron.interchaintxs.v1.MsgSubmitTx";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "from_address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "interchain_account_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "connection_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "msgs", kind: "message", T: Any, repeated: true },
    { no: 5, name: "memo", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "timeout", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 7, name: "fee", kind: "message", T: Fee },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MsgSubmitTx {
    return new MsgSubmitTx().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MsgSubmitTx {
    return new MsgSubmitTx().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MsgSubmitTx {
    return new MsgSubmitTx().fromJsonString(jsonString, options);
  }

  static equals(a: MsgSubmitTx | PlainMessage<MsgSubmitTx> | undefined, b: MsgSubmitTx | PlainMessage<MsgSubmitTx> | undefined): boolean {
    return proto3.util.equals(MsgSubmitTx, a, b);
  }
}

/**
 * MsgSubmitTxResponse defines the response for Msg/SubmitTx
 *
 * @generated from message neutron.interchaintxs.v1.MsgSubmitTxResponse
 */
export class MsgSubmitTxResponse extends Message<MsgSubmitTxResponse> {
  /**
   * channel's sequence_id for outgoing ibc packet. Unique per a channel.
   *
   * @generated from field: uint64 sequence_id = 1;
   */
  sequenceId = protoInt64.zero;

  /**
   * channel src channel on neutron side transaction was submitted from
   *
   * @generated from field: string channel = 2;
   */
  channel = "";

  constructor(data?: PartialMessage<MsgSubmitTxResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "neutron.interchaintxs.v1.MsgSubmitTxResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "sequence_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 2, name: "channel", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MsgSubmitTxResponse {
    return new MsgSubmitTxResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MsgSubmitTxResponse {
    return new MsgSubmitTxResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MsgSubmitTxResponse {
    return new MsgSubmitTxResponse().fromJsonString(jsonString, options);
  }

  static equals(a: MsgSubmitTxResponse | PlainMessage<MsgSubmitTxResponse> | undefined, b: MsgSubmitTxResponse | PlainMessage<MsgSubmitTxResponse> | undefined): boolean {
    return proto3.util.equals(MsgSubmitTxResponse, a, b);
  }
}

/**
 * MsgUpdateParams is the MsgUpdateParams request type.
 *
 * Since: 0.47
 *
 * @generated from message neutron.interchaintxs.v1.MsgUpdateParams
 */
export class MsgUpdateParams extends Message<MsgUpdateParams> {
  /**
   * Authority is the address of the governance account.
   *
   * @generated from field: string authority = 1;
   */
  authority = "";

  /**
   * params defines the x/interchaintxs parameters to update.
   *
   * NOTE: All parameters must be supplied.
   *
   * @generated from field: neutron.interchaintxs.v1.Params params = 2;
   */
  params?: Params;

  constructor(data?: PartialMessage<MsgUpdateParams>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "neutron.interchaintxs.v1.MsgUpdateParams";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "authority", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "params", kind: "message", T: Params },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MsgUpdateParams {
    return new MsgUpdateParams().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MsgUpdateParams {
    return new MsgUpdateParams().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MsgUpdateParams {
    return new MsgUpdateParams().fromJsonString(jsonString, options);
  }

  static equals(a: MsgUpdateParams | PlainMessage<MsgUpdateParams> | undefined, b: MsgUpdateParams | PlainMessage<MsgUpdateParams> | undefined): boolean {
    return proto3.util.equals(MsgUpdateParams, a, b);
  }
}

/**
 * MsgUpdateParamsResponse defines the response structure for executing a
 * MsgUpdateParams message.
 *
 * Since: 0.47
 *
 * @generated from message neutron.interchaintxs.v1.MsgUpdateParamsResponse
 */
export class MsgUpdateParamsResponse extends Message<MsgUpdateParamsResponse> {
  constructor(data?: PartialMessage<MsgUpdateParamsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "neutron.interchaintxs.v1.MsgUpdateParamsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MsgUpdateParamsResponse {
    return new MsgUpdateParamsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MsgUpdateParamsResponse {
    return new MsgUpdateParamsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MsgUpdateParamsResponse {
    return new MsgUpdateParamsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: MsgUpdateParamsResponse | PlainMessage<MsgUpdateParamsResponse> | undefined, b: MsgUpdateParamsResponse | PlainMessage<MsgUpdateParamsResponse> | undefined): boolean {
    return proto3.util.equals(MsgUpdateParamsResponse, a, b);
  }
}

